# Generated by Django 5.1.3 on 2024-11-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_user_profile_alter_booking_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
