# Generated by Django 5.1.3 on 2024-11-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_property_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_7',
        ),
        migrations.AlterField(
            model_name='property',
            name='image_1',
            field=models.ImageField(blank=True, default='property_images/default_property.png', null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('not_booked', 'Not Booked'), ('pending', 'Pending'), ('sold', 'Sold'), ('available', 'Available'), ('reserved', 'Reserved')], default='not_booked', max_length=50),
        ),
    ]
