# Generated by Django 5.1.3 on 2024-11-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_user_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='join_date',
            field=models.DateField(auto_now=True),
        ),
    ]
