# Generated by Django 5.1.3 on 2024-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_remove_user_profile_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='user_type',
            field=models.CharField(choices=[('general', 'General User'), ('landlord', 'Landlord')], default='general', max_length=10),
        ),
    ]
